#pragma once
#pragma warning
#include <GLFW/glfw3.h>
#include <ImGui/imgui.h>
#include <ImGui/imgui_impl_glfw.h>
#include <ImGui/imgui_impl_opengl3.h>
#include <ctime>
#include <fstream>
#include <iostream>
#include <PeriodTracker/PeriodTracker.hpp>
#include <vector>
#include <algorithm>
#include <cstdio>
#include <sys/stat.h>