#pragma once
#include <GLFW/glfw3.h>
#include <ImGui/imgui.h>
#include <ImGui/imgui_impl_glfw.h>
#include <ImGui/imgui_impl_opengl3.h>
#include <GLFW/glfw3.h>
#include <chrono>
#include <ctime>
#include <fstream>
#include <vector>
#include <PeriodTracker.h>
#include <iostream>
#include <MyApp.h>